### ISSUE TITLE
SPFX - PnP JS Core for SPFx On-Premise v1.0.2

### ISSUE THREAD

**Issue by geogikk92** [SharePoint/PnP-JS-Core#600]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

-----------------------------------------------------------------------------------------------------------

I want to use PnP JS Core in SPFx **v1.0.2** React webpart for SP16 On-premise server .

What is the version of pnp need to use and how to install it?
What are the other options for accessing data in SP with this version(1.0.2)?

> [13:16:05] [typescript] TypeScript version: 2.1.6
[13:16:05] Finished subtask 'copy-static-assets' after 588 ms
[13:16:07] Error - typescript - node_modules\sp-pnp-js\lib\graph\attachments.d.ts(1,42): error TS2307: Cannot find module '@microsoft/microsoft-graph-types'.
[13:16:07] Error - typescript - node_modules\sp-pnp-js\lib\graph\calendars.d.ts(2,32): error TS2307: Cannot find module '@microsoft/microsoft-graph-types'.
[13:16:07] Error - typescript - node_modules\sp-pnp-js\lib\graph\conversations.d.ts(3,98): error TS2307: Cannot find module '@microsoft/microsoft-graph-types'.
[13:16:07] Error - typescript - node_modules\sp-pnp-js\lib\graph\groups.d.ts(5,32): error TS2307: Cannot find module '@microsoft/microsoft-graph-types'.
[13:16:07] Finished subtask 'tslint' after 1.81 s
[13:16:07] Error - 'typescript' sub task errored after 1.82 s
 TypeScript error(s) occurred.
[13:16:07] 'bundle' errored after 2.4 s
[13:16:07]

**Comment by patrick-rodgers** [comment]
What version did you try this with? If it is 3.0.0 this might be related to #595 and I plan to get a patched version out today (3.0.1).

**Comment by geogikk92** [comment]
Hi, Patrick Rodhers! This post solve my problem: [https://sharepoint.stackexchange.com/questions/226189/spfx-pnp-js-core-for-spfx-on-premise-v1-0-2](Here)

**Comment by patrick-rodgers** [comment]
Ok, thanks. I'll try and see what wasn't working with 3.0.0 because obviously want to get it fixed. Thanks!

**Comment by patrick-rodgers** [comment]
I have confirmed that the addition of the `@microsoft/microsoft-graph-types --save` dependency has resolved the you had. The 3.0.1 version will be pushed later this afternoon. So you can use 3.0.1 in SPFx without issue. Sorry for the issue.
