### ISSUE TITLE
Issue with typescript 2.2.1

### ISSUE THREAD

**Issue by baywet** [SharePoint/PnP-JS-Core#331]
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
All my automated build started failing today as typescript 2.2.1 has been released. I fixed it taking of the ^ in front of the typescript version and fixing it to 2.2.0.

#### Observed Behavior
All builds report the same error message:
```
ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (11168,11): error TS2300: Duplicate identifier 'Headers'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (11177,13): error TS2300: Duplicate identifier 'Headers'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (13544,11): error TS2300: Duplicate identifier 'ReadableStream'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (13550,13): error TS2300: Duplicate identifier 'ReadableStream'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (13566,11): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (13583,13): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (13588,11): error TS2300: Duplicate identifier 'Response'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (13599,13): error TS2300: Duplicate identifier 'Response'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19116,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19121,6): error TS2300: Duplicate identifier 'BodyInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19142,6): error TS2300: Duplicate identifier 'HeadersInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19152,6): error TS2300: Duplicate identifier 'RequestInfo'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-streams\index.d.ts
2017-02-22T19:14:12.5236550Z (32,15): error TS2300: Duplicate identifier 'ReadableStream'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (13,14): error TS2300: Duplicate identifier 'HeadersInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (14,15): error TS2300: Duplicate identifier 'Headers'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (31,14): error TS2300: Duplicate identifier 'BodyInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (43,14): error TS2300: Duplicate identifier 'RequestInfo'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (44,15): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (64,11): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (88,15): error TS2300: Duplicate identifier 'Response'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (107,11): error TS2300: Duplicate identifier 'Response'.
```

#### Steps to Reproduce
Set up a project relying on sp-pnp-js and typescript. upgrade to latest versions of all (typescript@2.2.1, sp-pnp-js@2.0.1) and you'll get this error.
I'm building using webpack 2.

**Comment by patrick-rodgers** [comment]
Was 2.0.1 working before the latest TypeScript release?

**Comment by baywet** [comment]
Yes it was working with Typescript 2.1.5 2.1.6 and 2.2.0 (not sure for this one) and sp-pnp-js 2.0.0 and 2.0.1 (we have multiple active projects)

**Comment by patrick-rodgers** [comment]
Ok, thanks. I guess for now avoid TS 2.2.1. Will have to some testing.

**Comment by parkerbossier** [comment]
I can confirm that I'm seeing the same issue in 2.2.1, but *not* in 2.2.0.

**Comment by patrick-rodgers** [comment]
On this one they updated the .d.ts in a way that now conflicts with the @types we are including for fetch. Which is tough, because now we can remove the @types and update the lib to fix this for TS = 2.2.1 but will possibly break everyone not using TS 2.2.1. And I worry that TS will reverse this change in the future (say 2.2.2) - hard to say since it just happened in a minor release.

I am going to fix this in a local branch and wait and see for now.

**Comment by patrick-rodgers** [comment]
In fact they just added the below lines, didn't exist before 2.2.1:

```
interface Request extends Object, Body {
    readonly cache: string;
    readonly credentials: string;
    readonly destination: string;
    readonly headers: Headers;
    readonly integrity: string;
    readonly keepalive: boolean;
    readonly method: string;
    readonly mode: string;
    readonly redirect: string;
    readonly referrer: string;
    readonly referrerPolicy: string;
    readonly type: string;
    readonly url: string;
    clone(): Request;
}

declare var Request: {
    prototype: Request;
    new(input: Request | string, init?: RequestInit): Request;
}

interface Response extends Object, Body {
    readonly body: ReadableStream | null;
    readonly headers: Headers;
    readonly ok: boolean;
    readonly status: number;
    readonly statusText: string;
    readonly type: string;
    readonly url: string;
    clone(): Response;
}

declare var Response: {
    prototype: Response;
    new(body?: any, init?: ResponseInit): Response;
}

...

interface GlobalFetch {
    fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
}
```

**Comment by patrick-rodgers** [comment]
Closing as fixed in dev branch (#334), will be part of 2.0.2 release in March.

**Comment by costerik** [comment]
I haved the same issue and was solved it with this configuration.

package.json
{
  "name": "angular_2_app",
  "version": "1.0.0",
  "description": "angular app for presentation",
  "scripts": {
    "build": "tsc --rootDir src/ --outDir build/"
  },
  "author": "Erik Ahumada",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@types/node": "^7.0.11",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.39",
    "typescript": "^2.2.1",
    "typings": "^2.1.0",
    "webpack": "^2.3.2"
  }
}

tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "lib": ["es2015", "dom"]
    }
}
