### PR TITLE
fixing issue 331

### LINKED ISSUE #331: Issue with typescript 2.2.1
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
All my automated build started failing today as typescript 2.2.1 has been released. I fixed it taking of the ^ in front of the typescript version and fixing it to 2.2.0.

#### Observed Behavior
All builds report the same error message:
```
ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (11168,11): error TS2300: Duplicate identifier 'Headers'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (11177,13): error TS2300: Duplicate identifier 'Headers'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (13544,11): error TS2300: Duplicate identifier 'ReadableStream'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (13550,13): error TS2300: Duplicate identifier 'ReadableStream'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5080324Z (13566,11): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5080324Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (13583,13): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (13588,11): error TS2300: Duplicate identifier 'Response'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (13599,13): error TS2300: Duplicate identifier 'Response'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19116,18): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19121,6): error TS2300: Duplicate identifier 'BodyInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19142,6): error TS2300: Duplicate identifier 'HeadersInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\typescript\lib\lib.d.ts
2017-02-22T19:14:12.5236550Z (19152,6): error TS2300: Duplicate identifier 'RequestInfo'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-streams\index.d.ts
2017-02-22T19:14:12.5236550Z (32,15): error TS2300: Duplicate identifier 'ReadableStream'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (11,13): error TS2451: Cannot redeclare block-scoped variable 'fetch'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (13,14): error TS2300: Duplicate identifier 'HeadersInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (14,15): error TS2300: Duplicate identifier 'Headers'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (31,14): error TS2300: Duplicate identifier 'BodyInit'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (43,14): error TS2300: Duplicate identifier 'RequestInfo'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (44,15): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (64,11): error TS2300: Duplicate identifier 'Request'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (88,15): error TS2300: Duplicate identifier 'Response'.
2017-02-22T19:14:12.5236550Z ERROR in C:\agent\_work\12\s\node_modules\@types\whatwg-fetch\index.d.ts
2017-02-22T19:14:12.5236550Z (107,11): error TS2300: Duplicate identifier 'Response'.
```

#### Steps to Reproduce
Set up a project relying on sp-pnp-js and typescript. upgrade to latest versions of all (typescript@2.2.1, sp-pnp-js@2.0.1) and you'll get this error.
I'm building using webpack 2.

### PR DESCRIPTION
**Pull request by patrick-rodgers**
| Q               | A
| --------------- | ---
| Bug fix?        | [X]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #331 

#### What's in this Pull Request?

Makes updates to work with TS 2.2.1 where types for fetch were introduced to the core .d.ts file for es6.

### CODE REVIEW

**Comment by dev4201** [comment]
@patrick-rodgers - newbee question - how can I reference/use this fix in my package.json?

Thanks,
Dan

**Comment by patrick-rodgers** [comment]
@dev4201 when the next version is released (March 10 unless something goes wrong) you will just need to update the reference in your project to the latest npm package and you should be all set.

[docs](https://docs.npmjs.com/cli/update)

**Comment by lionhive** [comment]
Same problem with 2.2.1, many conflict errors:

node_modules/@types/isomorphic-fetch/index.d.ts(23,14): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/@types/isomorphic-fetch/index.d.ts(24,14): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/@types/isomorphic-fetch/index.d.ts(28,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'string[] | Headers | { [index: string]: string; }'.
