### ISSUE TITLE
The property 'EnableFql' does not exist on type 'Microsoft.Office.Server.Search.REST.SearchRequest'. 

### ISSUE THREAD

**Issue by dpalfery** [SharePoint/PnP-JS-Core#524]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.6         ]

#### Expected / Desired Behavior / Question

const appSearchSettings : SearchQuery = {
        TrimDuplicates: false,
        Querytext: "*",
        SourceId: resultsSource
      };
let q = SearchQueryBuilder.create(query, appSearchSettings);
      pnp.sp.search(q)
        .then(h => {
          resolve(h);
        })
        .catch(e =>{ 
        console.log(e);
        });
#### Observed Behavior
"The property 'EnableFql' does not exist on type 'Microsoft.Office.Server.Search.REST.SearchRequest'. Make sure to only use property names that are defined by the type."

#### Steps to Reproduce
This code works in version 2.0.5 of the library does not work in 2.0.6

**Comment by patrick-rodgers** [comment]
So you aren't setting the property EnableFQL, but you are getting that error? That is strange as I don't believe we made changes to search code that would affect that but let's see.

**Comment by patrick-rodgers** [comment]
Checked and that property definitely exists on the object - at least on the version of the source I am looking at. BUT on the object it is EnableFQL and we are sending EnableFql - which in this case matters. I didn't think we changed this, but anyway - fixed. I am also checking the other properties to ensure correct casing. I'll close this once I get the change merged. Thanks!
